#!/usr/bin/env sh

sudo yabai --load-sa

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=display_added   action="yabai --restart-service"
yabai -m signal --add event=display_removed action="yabai --restart-service"
yabai -m signal --add event=display_resized action="yabai --restart-service"
yabai -m signal --add event=display_moved   action="yabai --restart-service"

yabai -m config \
    external_bar                        all:0:0         \
    mouse_follows_focus                 on              \
    focus_follows_mouse                 on              \
    window_zoom_persist                 off             \
    window_placement                    second_child    \
    window_shadow                       on              \
    window_opacity                      off             \
    window_opacity_duration             0.2             \
    active_window_opacity               1.0             \
    normal_window_opacity               0.9             \
    window_animation_duration           0.0             \
    window_animation_easing             0xff9dd274      \
    split_ratio                         0.50            \
    auto_balance                        off             \
    mouse_modifier                      alt             \
    mouse_action1                       move            \
    mouse_action2                       resize          \
    mouse_drop_action                   swap            \
    top_padding                         8               \
    bottom_padding                      8               \
    left_padding                        8               \
    right_padding                       8               \
    window_gap                          10              \

yabai -m rule --add app=".*" sub-layer=normal
yabai -m rule --add app="^(System­einstellungen|Aktivitätsanzeige|FirstSpirit ServerManager|Raspberry|Raycast|Contexts|App Store)$" manage=off
yabai -m rule --add app="^(Citrix|Karabiner-Elements|Logitech G HUB)$" manage=off sub-layer=below
yabai -m rule --add label="Finder" app="^Finder$" title="Kopieren" manage=off
yabai -m rule --add app="^Slack$" title="^Huddle" manage=off

yabai -m config layout bsp
